# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

School.delete_all
Course.delete_all
User.delete_all
Role.delete_all

#@s = School.create(name:'IPT', country:'teste', distric:'teste',  city:'teste', county:'teste', postCode:'teste', addressDetails:'teste')
#@s.courses.create(name:'teste1')
#@r = Role.create(name: 'Admin')
#@r.users.create(name: 'teste', email: 'teste', password:'teste')

@s = School.create(name:'Escola Superior de Tecnologia de Tomar',country:'Portugal',district:'Santarém',city:'Tomar',county:'Tomar',postCode:'2300',addressDetails:'')
@s = School.create(name:'Escola Superior de Gestão de Tomar',country:'Portugal',district:'Santarém',city:'Tomar',county:'Tomar',postCode:'2300',addressDetails:'')
@s = School.create(name:'Escola Superior de Tecnologia de Abrantes',country:'Portugal',district:'Santarém',city:'Tomar',county:'Tomar',postCode:'2300',addressDetails:'')

@r1 = degree.create(name:'TeSP')
@r2 = degree.create(name:'Licenciatura')
@r3 = degree.create(name:'Mestrado')
@r4 = degree.create(name:'Doutoramento')
@r5 = degree.create(name:'Pós-Graduação')

@r1.courses.create(name:'Administração de Bases de Dados')
@r1.courses.create(name:'Animação e Modelação 3D')
@r1.courses.create(name:'Arte e Técnica do Couro')
@r1.courses.create(name:'Automação Industrial')
@r1.courses.create(name:'Construção e Reabilitação')
@r1.courses.create(name:'Contabilidade e Fiscalidade')
@r1.courses.create(name:'Contabilidade e Gestão')
@r1.courses.create(name:'Desenho Tecnológico')
@r1.courses.create(name:'Desenho e Fabrico de Construções Mecânicas')
@r1.courses.create(name:'Design Multimédia')
@r1.courses.create(name:'Gestão Administrativa de Recursos Humanos')
@r1.courses.create(name:'Gestão Comercial e Vendas')
@r1.courses.create(name:'Instalações Elétricas e Manutenção Industrial')
@r1.courses.create(name:'Manutenção de Sistemas Mecatrónicos')
@r1.courses.create(name:'Produção Artística para a Conservação e Restauro')
@r1.courses.create(name:'Produção de Atividades para o Turismo Cultural')
@r1.courses.create(name:'Qualidade Alimentar')
@r1.courses.create(name:'Qualidade Ambiental')
@r1.courses.create(name:'Segurança e Proteção Civil')
@r1.courses.create(name:'Som e Imagem')
@r1.courses.create(name:'Tecnologia de Bioprocessos')
@r1.courses.create(name:'Tecnologia e Programação em Sistemas de Informação')
@r1.courses.create(name:'Tecnologias Tradicionais de Construção e Reabilitação')
@r1.courses.create(name:'Web e Dispositivos Móveis')
@r2.courses.create(name:'Administração Pública')
@r2.courses.create(name:'Artes Plásticas - Pintura e Intermédia')
@r2.courses.create(name:'Auditoria e Fiscalidade')
@r2.courses.create(name:'Comunicação Social')
@r2.courses.create(name:'Conservação e Restauro')
@r2.courses.create(name:'Construção e Reabilitação')
@r2.courses.create(name:'Contabilidade')
@r2.courses.create(name:'Design e Tecnologia das Artes Gráficas')
@r2.courses.create(name:'Engenharia Civil (pós-laboral)')
@r2.courses.create(name:'Engenharia Civil')
@r2.courses.create(name:'Engenharia Electrotécnica e de Computadores (pós-laboral)')
@r2.courses.create(name:'Engenharia Electrotécnica e de Computadores')
@r2.courses.create(name:'Engenharia Informática (pós-laboral)')
@r2.courses.create(name:'Engenharia Informática')
@r2.courses.create(name:'Engenharia Mecânica')
@r2.courses.create(name:'Engenharia Química e Bioquímica')
@r2.courses.create(name:'Engenharia do Ambiente e Biológica')
@r2.courses.create(name:'Fotografia')
@r2.courses.create(name:'Gestão Turística e Cultural')
@r2.courses.create(name:'Gestão de Empresas (pós-laboral)')
@r2.courses.create(name:'Gestão de Empresas')
@r2.courses.create(name:'Gestão de Recursos Humanos e Comportamento Organizacional')
@r2.courses.create(name:'Gestão do Território')
@r2.courses.create(name:'Gestão e Administração Bancária (Pós-Laboral)')
@r2.courses.create(name:'Gestão e Administração de Serviços de Saúde')
@r2.courses.create(name:'Tecnologias de Informação e Comunicação')
@r2.courses.create(name:'Video e Cinema Documental')
@r3.courses.create(name:'Analítica e Inteligência Organizacional')
@r3.courses.create(name:'Arqueologia Pré-Histórica a Arte Rupestre')
@r3.courses.create(name:'Auditoria e Análise Financeira')
@r3.courses.create(name:'Auditoria e Finanças')
@r3.courses.create(name:'Conservação e Restauro')
@r3.courses.create(name:'Desenvolvimento de Produtos de Turismo Cultural')
@r3.courses.create(name:'Design Editorial')
@r3.courses.create(name:'Engenharia Eletrotécnica - Especialização em Controlo e Eletrónica Industrial')
@r3.courses.create(name:'Engenharia Informática - Internet das Coisas')
@r3.courses.create(name:'Engenharia Mecânica - Projecto e Produção Mecânica')
@r3.courses.create(name:'Fotografia')
@r3.courses.create(name:'Gestão de Empresas Familiares e Empreendedorismo')
@r3.courses.create(name:'Gestão de Recursos de Saúde')
@r3.courses.create(name:'Informática na Saúde (pós-laboral)')
@r3.courses.create(name:'Inovação e Desenvolvimento Empreendedor')
@r3.courses.create(name:'Manutenção de Instalações Técnicas')
@r3.courses.create(name:'Museus, Património e Sociedade do Conhecimento')
@r3.courses.create(name:'Produção de Conteúdos Digitais')
@r3.courses.create(name:'Reabilitação Urbana')
@r3.courses.create(name:'Sistemas de Informação Geográfica, em Planeamento e Gestão do Território')
@r3.courses.create(name:'Tecnologia Quimica')
@r3.courses.create(name:'Técnicas de Arqueologia')
@r5.courses.create(name:'Executive Master em Gestão de Organizações Sem Fins Lucrativos')
@r5.courses.create(name:'Executive Master em Gestão para Empreendedores e Executivos')
@r5.courses.create(name:'Análise e Tratamento Computacional de Dados')
@r5.courses.create(name:'Arqueologia Subaquática')
@r5.courses.create(name:'Arqueologia, Gestão e Educação Patrimonial')
@r5.courses.create(name:'Business Intelligence')
@r5.courses.create(name:'Design Multimédia')
@r5.courses.create(name:'Gestão de Informação e do Conhecimento')
@r5.courses.create(name:'Jornalismo de Proximidade')
@r5.courses.create(name:'Marketing Territorial')
@r5.courses.create(name:'Produção Industrial')
@r5.courses.create(name:'Proteção Civil: A Gestão da Comunicação no Risco, nas Emergências e nas Crises')
@r5.courses.create(name:'Pós-graduação em Novas Tecnologias da Comunicação')



puts "Success: seed data loaded"